"use strict";

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert("messages", [
      {
        nome: "Hélio Júnior",
        email: "helio.junior.ads@gmail.com",
        subject: "Assunto 01",
        content: "Conteúdo 01",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        nome: "Hélio Júnior",
        email: "helio.junior.ads@gmail.com",
        subject: "Assunto 01",
        content: "Conteúdo 01",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        nome: "Hélio Júnior",
        email: "helio.junior.ads@gmail.com",
        subject: "Assunto 01",
        content: "Conteúdo 01",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        nome: "Hélio Júnior",
        email: "helio.junior.ads@gmail.com",
        subject: "Assunto 01",
        content: "Conteúdo 01",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        nome: "Hélio Júnior",
        email: "helio.junior.ads@gmail.com",
        subject: "Assunto 01",
        content: "Conteúdo 01",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        nome: "Hélio Júnior",
        email: "helio.junior.ads@gmail.com",
        subject: "Assunto 01",
        content: "Conteúdo 01",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        nome: "Hélio Júnior",
        email: "helio.junior.ads@gmail.com",
        subject: "Assunto 01",
        content: "Conteúdo 01",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        nome: "Hélio Júnior",
        email: "helio.junior.ads@gmail.com",
        subject: "Assunto 01",
        content: "Conteúdo 01",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        nome: "Hélio Júnior",
        email: "helio.junior.ads@gmail.com",
        subject: "Assunto 01",
        content: "Conteúdo 01",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        nome: "Hélio Júnior",
        email: "helio.junior.ads@gmail.com",
        subject: "Assunto 01",
        content: "Conteúdo 01",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        nome: "Hélio Júnior",
        email: "helio.junior.ads@gmail.com",
        subject: "Assunto 01",
        content: "Conteúdo 01",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        nome: "Hélio Júnior",
        email: "helio.junior.ads@gmail.com",
        subject: "Assunto 01",
        content: "Conteúdo 01",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        nome: "Hélio Júnior",
        email: "helio.junior.ads@gmail.com",
        subject: "Assunto 01",
        content: "Conteúdo 01",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        nome: "Hélio Júnior",
        email: "helio.junior.ads@gmail.com",
        subject: "Assunto 01",
        content: "Conteúdo 01",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        nome: "Hélio Júnior",
        email: "helio.junior.ads@gmail.com",
        subject: "Assunto 01",
        content: "Conteúdo 01",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        nome: "Hélio Júnior",
        email: "helio.junior.ads@gmail.com",
        subject: "Assunto 01",
        content: "Conteúdo 01",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        nome: "Hélio Júnior",
        email: "helio.junior.ads@gmail.com",
        subject: "Assunto 01",
        content: "Conteúdo 01",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        nome: "Hélio Júnior",
        email: "helio.junior.ads@gmail.com",
        subject: "Assunto 01",
        content: "Conteúdo 01",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        nome: "Hélio Júnior",
        email: "helio.junior.ads@gmail.com",
        subject: "Assunto 01",
        content: "Conteúdo 01",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        nome: "Hélio Júnior",
        email: "helio.junior.ads@gmail.com",
        subject: "Assunto 01",
        content: "Conteúdo 01",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        nome: "Hélio Júnior",
        email: "helio.junior.ads@gmail.com",
        subject: "Assunto 01",
        content: "Conteúdo 01",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        nome: "Hélio Júnior",
        email: "helio.junior.ads@gmail.com",
        subject: "Assunto 01",
        content: "Conteúdo 01",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        nome: "Hélio Júnior",
        email: "helio.junior.ads@gmail.com",
        subject: "Assunto 01",
        content: "Conteúdo 01",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        nome: "Hélio Júnior",
        email: "helio.junior.ads@gmail.com",
        subject: "Assunto 01",
        content: "Conteúdo 01",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        nome: "Hélio Júnior",
        email: "helio.junior.ads@gmail.com",
        subject: "Assunto 01",
        content: "Conteúdo 01",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        nome: "Hélio Júnior",
        email: "helio.junior.ads@gmail.com",
        subject: "Assunto 01",
        content: "Conteúdo 01",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        nome: "Hélio Júnior",
        email: "helio.junior.ads@gmail.com",
        subject: "Assunto 01",
        content: "Conteúdo 01",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        nome: "Hélio Júnior",
        email: "helio.junior.ads@gmail.com",
        subject: "Assunto 01",
        content: "Conteúdo 01",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        nome: "Hélio Júnior",
        email: "helio.junior.ads@gmail.com",
        subject: "Assunto 01",
        content: "Conteúdo 01",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        nome: "Hélio Júnior",
        email: "helio.junior.ads@gmail.com",
        subject: "Assunto 01",
        content: "Conteúdo 01",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        nome: "Hélio Júnior",
        email: "helio.junior.ads@gmail.com",
        subject: "Assunto 01",
        content: "Conteúdo 01",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        nome: "Hélio Júnior",
        email: "helio.junior.ads@gmail.com",
        subject: "Assunto 01",
        content: "Conteúdo 01",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        nome: "Hélio Júnior",
        email: "helio.junior.ads@gmail.com",
        subject: "Assunto 01",
        content: "Conteúdo 01",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        nome: "Hélio Júnior",
        email: "helio.junior.ads@gmail.com",
        subject: "Assunto 01",
        content: "Conteúdo 01",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        nome: "Hélio Júnior",
        email: "helio.junior.ads@gmail.com",
        subject: "Assunto 01",
        content: "Conteúdo 01",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        nome: "Hélio Júnior",
        email: "helio.junior.ads@gmail.com",
        subject: "Assunto 01",
        content: "Conteúdo 01",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        nome: "Hélio Júnior",
        email: "helio.junior.ads@gmail.com",
        subject: "Assunto 01",
        content: "Conteúdo 01",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        nome: "Hélio Júnior",
        email: "helio.junior.ads@gmail.com",
        subject: "Assunto 01",
        content: "Conteúdo 01",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        nome: "Hélio Júnior",
        email: "helio.junior.ads@gmail.com",
        subject: "Assunto 01",
        content: "Conteúdo 01",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        nome: "Hélio Júnior",
        email: "helio.junior.ads@gmail.com",
        subject: "Assunto 01",
        content: "Conteúdo 01",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        nome: "Hélio Júnior",
        email: "helio.junior.ads@gmail.com",
        subject: "Assunto 01",
        content: "Conteúdo 01",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        nome: "Hélio Júnior",
        email: "helio.junior.ads@gmail.com",
        subject: "Assunto 01",
        content: "Conteúdo 01",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        nome: "Hélio Júnior",
        email: "helio.junior.ads@gmail.com",
        subject: "Assunto 01",
        content: "Conteúdo 01",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        nome: "Hélio Júnior",
        email: "helio.junior.ads@gmail.com",
        subject: "Assunto 01",
        content: "Conteúdo 01",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        nome: "Hélio Júnior",
        email: "helio.junior.ads@gmail.com",
        subject: "Assunto 01",
        content: "Conteúdo 01",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        nome: "Hélio Júnior",
        email: "helio.junior.ads@gmail.com",
        subject: "Assunto 01",
        content: "Conteúdo 01",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        nome: "Hélio Júnior",
        email: "helio.junior.ads@gmail.com",
        subject: "Assunto 01",
        content: "Conteúdo 01",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        nome: "Hélio Júnior",
        email: "helio.junior.ads@gmail.com",
        subject: "Assunto 01",
        content: "Conteúdo 01",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        nome: "Hélio Júnior",
        email: "helio.junior.ads@gmail.com",
        subject: "Assunto 01",
        content: "Conteúdo 01",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        nome: "Hélio Júnior",
        email: "helio.junior.ads@gmail.com",
        subject: "Assunto 01",
        content: "Conteúdo 01",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        nome: "Hélio Júnior",
        email: "helio.junior.ads@gmail.com",
        subject: "Assunto 01",
        content: "Conteúdo 01",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ]);
  },

  async down(queryInterface, Sequelize) {},
};
